apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogues
spec:
  selector:
    matchLabels:
      app: catalogue
  template:
    metadata:
      labels:
        app: catalogue
    spec:
      containers:
      - name: catalogue
        image: njokuiyke01/catalogue:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: MongoDbSettings__Host
            value: mongodb-service
          - name: MongodbSettings__Password
            valueFrom:
              secretKeyRef:
                name: catalogues-secrets
                key: mongodb-password
        livenessProbe:
          httpGet:
            path: /health/live
            port: 80
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 80               
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue-service
spec:
  type: LoadBalancer
  selector:
    app: catalogue
  ports:
  - port: 80
    targetPort: 80

